name: climush

services:
  climush-bioinformatics:
    platform: linux/amd64
    image: climush-bioinfo
    build:
      context: git@github.com:cdelevich/climush.git#main:/docker-containers/bioinformatics/app/
      ssh:
        - default
      args:
        - VERSION_NUM=0.1
        - USER=mycophile
    stdin_open: true
    tty: true
    volumes:
#      - type: bind
#        source: /home/mycophile/pipeline
#        target: "$(pwd)"
#      - type: bind
#        source: /home/mycophile/config
#        target: "$(pwd)"
#      - type: bind
#        source: /home/$USER/sequences
#        target: "$(pwd)"
#      - type: bind
#        source: /home/$USER/pipeline-output
#        target: "$(pwd)"
