[collection_date]
AK = "2023-08"
AZ = "2023-11"
CO = "2023-09"
FL = "2023-12"
KS = "2023-09"
MA = "2023-11"
MN = "2023-09"
OR = [ "2023-10", "2023-10" ]

[site_name]
AK = "BNZ"
AZ = "SRE"
CO = "NWT"
FL = "ORD"
KS = "KON"
MA = "HFMA"
MN = "CDR"
OR = [ "HJA", "PIS" ]

[component_positions]
seq_platform = nan
compartment  =  4
ecoregion    =  0
treatment    =  1
subplot      =  3

[delimiter]
delimiter = "_"

[accepted_labels]
ecoregion    = ""
seq_platform = ""                                # no label for the sequence platform in the original file name
treatment    = [ "B*", "U*", "*O", "*G", "*C" ]
subplot      = "S*"

[accepted_labels.compartment]
litter      = "L"
soil        = "S*"
spore       = ""
sporocarp-f = ""
sporocarp-a = ""
leaf-sp01   = ""
leaf-sp02   = ""
seed-sp01   = ""
seed-sp02   = ""
root-sp01   = ""
root-sp02   = ""

[missing_components]  # if any components missing from original file name, provide that information here
ecoregion    = ""
seq_platform = "illumina"
treatment    = ""
subplot      = ""